apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-clustering-replica
  namespace: redis
# data:
#   redis.conf: |+
#     masterauth  Securep@55Here
#     replicaof redis-clustering-master.redis.svc.cluster.local 6379
data:
  redis.conf: |+
    replicaof redis-clustering-master.redis.svc.cluster.local 6379
