---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csv-data-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/ubbe92/prototype-k8s-config/volumes/events_participants/csv_files" # replace with path on host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
