apiVersion: apps/v1
kind: Deployment
metadata:
  name: prototype-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prototype-client
  template:
    metadata:
      labels:
        app: prototype-client
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
      containers:
        - name: prototype-client
          image: ubbe92/prototype-client
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "800m"
          ports:
            - containerPort: 8080
          # command: ["/bin/sh", "-c", "ls /app/csv_files/*.csv && sleep 3600"]
          volumeMounts:
            - name: nfs-volume
              mountPath: /app/csv_files
          env:
            - name: NUM_WORKERS_REDIS
              value: "12"
            - name: NUM_WORKERS_ODDS
              value: "4"
            - name: QUERY_SENTINEL
              value: "true"
            - name: SHOW_DEBUG
              value: "false"
