apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-clustering-master
  namespace: redis
# data:
#   redis.conf: |
#     appendonly no
#     requirepass  Securep@55Here
#     protected-mode no
data:
  redis.conf: |
    appendonly no
    protected-mode no
