apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-clustering-master
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-clustering-master
  template:
    metadata:
      labels:
        app: redis-clustering-master
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
          command: ["redis-server", "/conf/redis.conf"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
      volumes:
        - name: conf
          configMap:
            name: redis-clustering-master
            defaultMode: 0755
